
# The name of your website.
name: Stijn van Cuijk, Industrial Designer

description:
  # Description of your site. This will show up in google.
  meta: Portfolio of Stijn van Cuijk, Master Student in Advanced Product Design at Umeå Institute of Design.

date_format: "%b %-d, %Y"

# The URL of the homepage of your site (without trailing slash). Leave this
# empty when you run Jekyll locally.
url: http://localhost:4000
baseurl: ""

collections:
  projects:
    output: true
    permalink: /:permalink
  ideas:
    output: true
    permalink: /:permalink
  old-projects:
    output: true
    permalink: /:permalink
  personal-projects:
    output: true
    permalink: /:permalink

##################
# BUILD SETTINGS #
##################

exclude: [vendor]
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
      excerpt_separator: "<!--more-->"
  - scope:
      path: ""
      type: "ideas"
    values:
      layout: "page"
      excerpt_separator: "<!--more-->"
  - scope:
      path: ""
      type: "personal-projects"
    values:
      layout: "page"
      excerpt_separator: "<!--more-->"
  - scope:
      path: ""
      type: "old-projects"
    values:
      layout: "page"
      excerpt_separator: "<!--more-->"
